Fixed Unity exception on call to `iplCreateContext`. (#114)
Exception: NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.

Cause: The call to `iplCreateContext` passes static method `LogCallback` which hasn't been annotated with the `MonoPInvokeCallback` attribute.

Fix: Annotate `LogCallback` with the `MonoPInvokeCallback` attribute. Tested with Unity 2018.3.14f1 and IL2CPP.

Co-authored-by: Jonas Johansson <jonas@neuston.io>